# Generated by Django 5.2.7 on 2025-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vegetales', 'Vegetales'), ('frutas', 'Frutas'), ('carnes', 'Carnes'), ('legumbres', 'Legumbres'), ('cereales', 'Cereales'), ('condimentos', 'Condimentos'), ('especias', 'Especias')], max_length=20),
        ),
    ]
