# Generated by Django 5.2.7 on 2025-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattel', '0003_alter_contacto_id_alter_producto_id_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], default='Fácil', max_length=20),
        ),
        migrations.AddField(
            model_name='receta',
            name='pasos',
            field=models.TextField(default='1. Preparar ingredientes\n2. Mezclar\n3. Cocinar', help_text='Escribe cada paso en una nueva línea.'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo',
            field=models.CharField(default='30 minutos', max_length=50),
        ),
    ]
