# Generated by Django 5.2.7 on 2025-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattel', '0004_receta_dificultad_receta_pasos_receta_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('ensalada', 'Ensalada'), ('guisado', 'Guisado'), ('sopa', 'Sopa'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('sandwich', 'Sandwich'), ('pasta', 'Pasta'), ('carne', 'Carne'), ('mariscos', 'Mariscos'), ('vegana', 'Vegana'), ('pizza', 'Pizza'), ('tacos', 'Tacos'), ('wrap', 'Wrap'), ('arroz', 'Arroz'), ('cereal', 'Cereal'), ('pan', 'Pan'), ('dulce', 'Dulce'), ('salado', 'Salado'), ('light', 'Light'), ('rápida', 'Rápida')], default='ensalada', max_length=50),
        ),
    ]
